Document: shaderc
Title: Debian shaderc Manual
Author: <insert document author here>
Abstract: This manual describes what shaderc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/shaderc/shaderc.sgml.gz

Format: postscript
Files: /usr/share/doc/shaderc/shaderc.ps.gz

Format: text
Files: /usr/share/doc/shaderc/shaderc.text.gz

Format: HTML
Index: /usr/share/doc/shaderc/html/index.html
Files: /usr/share/doc/shaderc/html/*.html
